### ISSUE TITLE
About Valum as a subproject.

### ISSUE THREAD

**Issue by dreamer-coding** [geoffjay/icd#6]
I'm wondering why where not depending on the Valum wrap file to handle getting that dependency in the Dockerfile declaration?

**Comment by geoffjay** [comment]
No good reason really. At the time this was written I found it slightly more complicated to set up for local builds, I've just never gone back and updated it for wrap files. I think it would be better if both Valum and the Template-GLib libraries were handled that way.

**Comment by dreamer-coding** [comment]
I believe this had been handled with commit #8
